"""add email verification fields

Revision ID: 884964e7de67
Revises: 
Create Date: 2026-07-10 22:21:07.503781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884964e7de67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verifie', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('code_verification', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('code_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('code_expiration')
        batch_op.drop_column('code_verification')
        batch_op.drop_column('email_verifie')

    # ### end Alembic commands ###
