"""datetime timezone aware

Revision ID: b43603ac2874
Revises: 9dd869f9ccd8
Create Date: 2026-07-12 15:18:12.782129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43603ac2874'
down_revision = '9dd869f9ccd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=200), nullable=False),
    sa.Column('zone_depart', sa.String(length=100), nullable=False),
    sa.Column('est_conducteur', sa.Boolean(), nullable=True),
    sa.Column('vehicule', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email_verifie', sa.Boolean(), nullable=True),
    sa.Column('code_verification', sa.String(length=6), nullable=True),
    sa.Column('code_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_code', sa.String(length=6), nullable=True),
    sa.Column('reset_code_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trajet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depart', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('heure', sa.String(length=10), nullable=False),
    sa.Column('places_disponibles', sa.Integer(), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=True),
    sa.Column('conducteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conducteur_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_reservation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_specifique', sa.String(length=20), nullable=True),
    sa.Column('passager_id', sa.Integer(), nullable=False),
    sa.Column('trajet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['trajet_id'], ['trajet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trajet_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trajet_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trajet_id'], ['trajet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('trajet_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('cible_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cible_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.ForeignKeyConstraint(['trajet_id'], ['trajet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avis')
    op.drop_table('trajet_log')
    op.drop_table('reservation')
    op.drop_table('trajet')
    op.drop_table('user')
    # ### end Alembic commands ###
